# Generated by Django 4.2.4 on 2023-08-12 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0002_car_created_at_car_model_model_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="brand",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Showroom.brand",
            ),
        ),
    ]
