# Generated by Django 4.2.4 on 2023-08-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0006_remove_brand_showroom_brand_showroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="showroom",
        ),
        migrations.AddField(
            model_name="showroom",
            name="brands",
            field=models.ManyToManyField(default="", to="Showroom.brand"),
        ),
    ]
