# Generated by Django 4.2.4 on 2023-08-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0007_remove_brand_showroom_showroom_brands"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="showroom",
            name="brands",
        ),
        migrations.AddField(
            model_name="showroom",
            name="brand",
            field=models.ManyToManyField(
                default="", related_name="brand", to="Showroom.brand"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="model",
            field=models.ManyToManyField(related_name="model", to="Showroom.model"),
        ),
    ]
