# Generated by Django 4.2.4 on 2023-08-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0008_remove_showroom_brands_showroom_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroom",
            name="brand",
            field=models.ManyToManyField(default="", to="Showroom.brand"),
        ),
        migrations.AlterField(
            model_name="showroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Joining Date"),
        ),
    ]
