# Generated by Django 4.2.4 on 2023-08-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0009_alter_showroom_brand_alter_showroom_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Joining Date"),
        ),
    ]
