# Generated by Django 4.2.4 on 2023-08-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0010_alter_showroom_created_at_alter_staff_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="engine",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Showroom.engine",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="feature",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Showroom.feature",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Brand"),
        ),
        migrations.AlterField(
            model_name="engine",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Engine"),
        ),
        migrations.AlterField(
            model_name="feature",
            name="model",
            field=models.ManyToManyField(to="Showroom.model"),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Model"),
        ),
    ]
