# Generated by Django 4.2.4 on 2023-08-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0012_remove_car_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="stock",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
