# Generated by Django 4.2.4 on 2023-08-14 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0013_car_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="engine",
        ),
    ]
