# Generated by Django 4.2.4 on 2023-08-14 07:17

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0014_remove_car_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(
                default="",
                upload_to=pathlib.PureWindowsPath(
                    "D:/Codes/Django/Django-Course/Assignment 2/media"
                ),
            ),
        ),
    ]
