# Generated by Django 4.2.4 on 2023-08-14 08:22

import Showroom.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0015_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="image",
            field=models.ImageField(
                default="", upload_to=Showroom.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                default="", upload_to=Showroom.models.user_directory_path
            ),
        ),
    ]
