# Generated by Django 4.2.4 on 2023-08-14 10:41

import Showroom.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Showroom", "0016_staff_image_alter_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                default="", upload_to=Showroom.models.user_directory_path
            ),
        ),
    ]
